### ISSUE TITLE
Support capturing stdout

### ISSUE THREAD

**Issue by tionis** [meinside/telegram-janet-repl-bot#2]
Using the dynamic binding \*out\* you could capture all the output without needing to overwrite the environment  
[documentation](https://janet-lang.org/api/index.html#*out*)

**Comment by meinside** [comment]
Hi @tionis, thanks for the issue.

I'd like to remove function overrides, but cannot find good examples of replacing \*out\* in this situation.

If I bind \*out\* a new buffer, for example, what could be the best practice of polling updates from that buffer? Or is there any good solution for it?

**Comment by tionis** [comment]
I thought you could use streams for this, but I couldn't get it to work in my env.

**Comment by meinside** [comment]
Too late, but removed overridden functions by using dynamic binding of \*out\* with:

https://github.com/meinside/telegram-janet-repl-bot/compare/v0.0.9...v0.1.0
